version : '3'

services:
    mysql:
        image: mysql:latest
        restart: always
        container_name: dev_mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: default_schema
        volumes:
            - mysql-data:/var/lib/mysql
            - ./db-init:/docker-entrypoint-initdb.d
        networks:
            - backend
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dev_pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        networks:
            - backend
        ports:
            - 8183:80
    
    app:
        build: .
        container_name: flask_app
        volumes:
            - ./:/app
        networks:
            - backend
        ports:
            - 5000:5000

volumes:
    mysql-data:

networks:
    backend:
